#!/bin/sh
#
# 根据 commitmsg 以及 branch name 判断是否需要 commitlint
#
# Author: waiting
# Date: 2023.07.21
#

branch=$( git branch | grep \* | cut -d ' ' -f2 )
# ./.githooks/init-repo/is-skip-commitlint.ts $1 "$branch"

# code=$?
code=0
#echo -e 'node exitCode:' $code

if [[ $code = 0 ]] && [[ -d node_modules ]] ; then
  commitlint -e ./.git/COMMIT_EDITMSG
fi

