
bail: true
full-trace: true
enable-source-maps: true
node-option:
  - no-warnings
  - "loader=ts-node/esm"
require:
  - tsconfig-paths/register.js
  - test/setup.mts
# loader:
#  - ts-node/esm
spec:
  - test/**/*.test.ts
timeout: 90000
ui: bdd
parallel: true
exit: true

