clone_folder: c:\projects\myproject
shallow_clone: true

init:
  - git config --global core.autocrlf input

cache:
  - node_modules                        # local npm modules
  - '%APPDATA%\npm-cache'               # npm cache


environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "12"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm root -g
  - npm i rollup typescript eslint nyc
  - npm install

#services:
#  - postgresql101
#
before_test:
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - SET PATH=C:\Program Files\PostgreSQL\10\bin\;%PATH%
  #- psql -U postgres -c "create database db_ci_test;"

test_script:
  - openssl version
  - node --version
  - npm --version
  - npm run build
  #- npm run test

on_success:
  - npm run cov:coveralls

build: off
deploy: off
skip_tags: true

