clone_folder: c:\projects\myproject
shallow_clone: true

init:
  - git config --global core.autocrlf input

cache:
  - node_modules                        # local npm modules
  - '%APPDATA%\npm-cache'               # npm cache


environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"
    # https://github.com/appveyor/ci/issues/2921
    #- nodejs_version: "12"

platform:
  - x64
  - x86

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm root -g
  - npm i rollup typescript eslint nyc
  - npm install

test_script:
  - openssl version
  - node --version
  - npm --version
  - npm run build
  #- npm run test

on_success:
  - npm run cov:coveralls

build: off
deploy: off
skip_tags: true

