
bail: true
full-trace: true
enable-source-maps: true
require:
  # for cjs
  - ts-node/register
  - tsconfig-paths/register.js
  - test/root.hooks.ts
spec:
  - test/**/*.test.ts
timeout: 120000
ui: bdd
parallel: false
exit: true

