# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: manual-publish

on:
  workflow_dispatch:
    inputs:
      semver:
        description: 'Leave empty or input major|minor|patch'
        required: false
        default: ''

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container: node:current
    timeout-minutes: 60

    strategy:
      matrix:
        node: ['lts/*']
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          # pulls all commits (needed for lerna / semantic release to correctly version)
          fetch-depth: "0"
      # Caution: disable fix below at FIRST publish, then enable
      - name: Fix for semantic release
        # pulls all tags (needed for lerna / semantic release to correctly version)
        run: |
          export cwd=`pwd`
          git config --global --add safe.directory $cwd || true
          git fetch --depth=1 origin +refs/tags/*:refs/tags/* || true
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'

      - name: Cache
        uses: actions/cache@v4
        id: cache-lerna
        env:
          cache-name: cache-lerna
        with:
          path: |
            node_modules
            package-lock.json
          key: ${{ runner.OS }}-build-${{ env.cache-name }}-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-${{ github.ref }}-

      - name: Prepare
        run: |
          uname -a
          export DEBIAN_FRONTEND=noninteractive
          apt-get update -qq --yes > /dev/null
          # apt-get upgrade -qq --yes > /dev/null
          apt-get install -qq --yes --no-install-recommends bash dnsutils git jq locales net-tools wget > /dev/null
          apt-get install -qq --yes postgresql-client libpq-dev > /dev/null
          uname -a
          npm -v && node -v
          git --version
          openssl version
          cat /etc/*release
          sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen
          locale-gen
          locale -a
          netstat -tunpl
          # chmod a+w -R .
          dig jaeger

      - name: Verify
        run: |
          echo $GITHUB_REF
          # github project/settings/Secrets/New repository secret: NPM_TOKEN
          npm ping
          dig httpbin
          curl http://httpbin/get
          npm whoami
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install Dependencies
        timeout-minutes: 15
        run: |
          # chmod a+w -R .
          export cwd=`pwd`
          npm i --no-audit -g autocannon c8 lerna rollup tsx zx
          npm i --no-audit
        env:
          CI: true

      - name: Build
        run: |
          whoami
          export cwd=`pwd`
          . .scripts/ci/ci-env.sh
          .scripts/ci/ci-prepare.sh
          npm run build --if-present
        env:
          CI: true

      - name: Lint
        run: |
          export cwd=`pwd`
          . .scripts/ci/ci-env.sh
          .scripts/ci/ci-prepare.sh
          npm run lint:nofix
          npm run lint:cycle
        env:
          CI: true

      # - name: Init Database
      #   run: |
      #     export cwd=`pwd`
      #     . .scripts/ci/ci-env.sh
      #     .scripts/ci/ci-prepare.sh
      #     .scripts/ci/ci-init-db.sh
      #   env:
      #     CI: true
      #     POSTGRES_HOST: postgres
      #     POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
      #     POSTGRES_DB: db_ci_test
      #     POSTGRES_USER: postgres
      #     POSTGRES_PASSWORD: postgres
      #     PGPASSWORD: postgres

      - name: Testing
        run: |
          export cwd=`pwd`
          . .scripts/ci/ci-env.sh
          .scripts/ci/ci-prepare.sh
          # npm run ci
          npm run test
        env:
          CI: true
          HTTPBIN_HOST: httpbin
          # otel
          OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317

      - name: NPM Publish
        run: |
          npm ping
          npm whoami
          export cwd=`pwd`
          . .scripts/ci/ci-env.sh
          # fix: fatal: detected dubious ownership in repository
          git config --global --add safe.directory $cwd
          # git restore .
          git reset --hard
          git config user.name $GITHUB_ACTOR
          git config user.email gh-actions-${GITHUB_ACTOR}@github.com
          # npm run pub major
          rm -rf package-lock.json
          rm -rf packages/*/package-lock.json
          .scripts/publish.sh --yes --no-private --conventional-commits --create-release github ${{ github.event.inputs.semver }}
          git push -v origin --follow-tags
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}



    services:
      httpbin:
        image: kennethreitz/httpbin
        ports:
          - 80:80 # no 443

      jaeger:
        image: jaegertracing/all-in-one
        env:
          TZ: 'Asia/Chongqing'
          COLLECTOR_OTLP_ENABLED: 'true'
        ports:
          - 4317:4317
          - 4318:4318
          - 5778:5778
          - 6831:6831/udp
          - 6832:6832/udp
          - 14250:14250
          - 16686:16686

